---
title: "Cleaning Data"
author: "Danielle Reimanis"
date: "10/17/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(dplyr)
library(tidyverse)
library(tidyr)
library(lubridate)
library(xts)
library(dygraphs)
library(sf)
library(raster)
library(USAboundaries)
library(mapview)


```

# Cleaning data, selecting relevant observations, joining to long

```{r}

files <- list.files('data',full.names = T)

my_reader <- function(file){
  data_names = str_split_fixed(file,'_',2)[,1]
  name = gsub('data/','',data_names)
  df <- read_csv(file,) %>%
    dplyr::select(address, name, version, logging_interval)%>%
    rename('date' = 1,
           'temp' = 2,
           'humidity' = 3,
           'dewpoint' = 4) %>%
    mutate(temp = as.numeric(temp))%>%
    mutate(humidity = as.numeric(humidity))%>%
    mutate(dewpoint = as.numeric(dewpoint))%>%
    slice(-1,-2)%>%
    mutate(site = name)%>%
    mutate(site = replace(site, list=site=="BN29", values="BM29"))
  return(df)
}

data_clean <- map_dfr(files,my_reader)

```

# Random Fixes
```{r}
#BM42, 43, 44 had dewpoints of 700 and higher, so i removed
dewpoint_analysis <- data_clean %>%
  filter(., !site == "BM42",
         !site == "BM43",
         !site == "BM44")

#bm21 calculated temp every 10 minutes, so I took average to get hourly
bm21_hourly <- data_clean %>%
  filter(site == "BM21")%>%
  mutate(date = ymd_hm(date, tz='MST'))%>%
  mutate(hour = hour(date))%>%
  mutate(day = day(date))%>%
  mutate(month = month(date))%>%
  group_by(site, month, day, hour)%>%
  summarize(mean_temp = mean(temp))%>%
  as.data.frame()%>%
  as.tibble()

```

# Pulling Elevation Data

```{r}



```



```{r}
# looking at temperature only
temp <- data_clean%>%
  dplyr::select(date, temp, site) %>%
  filter(!site == "BM21")%>%
  mutate(date = ymd_hm(date, tz='MST'))

temp_means <- temp %>%
  mutate(month = month(date))%>%
  group_by(month, site)%>%
  summarise(mean_temp = mean(temp))

temp_max <- temp %>%
  mutate(month = month(date))%>%
  group_by(month, site)%>%
  summarise(max_temp = max(temp))

temp_min <- temp %>%
  mutate(month = month(date))%>%
  group_by(month, site)%>%
  summarise(min_temp = min(temp))

ggplot(temp_means, aes(x=month, y=mean_temp, color=site))+
  geom_line()

ggplot(temp_max, aes(x=month, y=max_temp, color=site))+
  geom_line()

ggplot(temp_min, aes(x=month, y=min_temp, color=site))+
  geom_line()

```

# dygraph of temp vs time

```{r}
temp_wide <- temp %>%
  spread(., key='site',
         value='temp')%>%
  filter_if(is.numeric, all_vars(!is.na(.)))

temp_xts <- temp_wide %>%
  xts(., order.by = .$date)

dygraph(data_xts)%>%
  dyAxis('y', label='Temperature (°C)', valueRange=c(-15,40))

# min_temp <- temp_wide %>%
#   filter(BM44 == -14.50)

```



```{r}
#location data frame

utmE <- c(449451, 449437, 449220, 449008, 448513, 448198, 447880, 446903,
          449429, 448272, 447472)

utmN <- c(4491181, 4491210, 4491086, 4490502, 4489917, 4489759, 4489705,
          4489234, 4491265, 4489694, 4489393)

elev <- c(2787, 2789, 2837, 2853, 2889, 2907, 2911, 3001, 2796.2, 2873,
          2955)

site <- c('BM25', 'BM26', 'BM28', 'BM29', 'BM30', 'BM31', 'BM32', 
          'BM33', 'BM42', 'BM43', 'BM44')

location_data <- cbind(site, utmE, utmN, elev) %>%
  as.data.frame()

location_data_num <- location_data %>%
  mutate(site = as.character(site),
         utmE = as.numeric(as.character(utmE)),
         utmN = as.numeric(as.character(utmN)),
         elev = as.numeric(as.character(elev)))

str(location_data_num)
```

# Making spatial points
```{r}

spatial_points <- location_data_num %>%
  st_as_sf(coords=c('utmE','utmN'), crs=26913)

mapview(spatial_points)

```

